#!/usr/bin/env bash

FNL_VERSION=1.6.1
FNL_NAME=fennel-$FNL_VERSION

# Executable binary
curl https://fennel-lang.org/downloads/$FNL_NAME >script/fennel.lua
chmod +x script/fennel.lua

# Compiler / library
curl https://fennel-lang.org/downloads/$FNL_NAME.lua >lua/nfnl/fennel.lua

# Embedify the Fennel library by replacing `fennel.*` with `nfnl.fennel.*`.
sd '"fennel\.' '"nfnl.fennel.' lua/nfnl/fennel.lua
